// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myrmica.Data;

namespace Myrmica.Services.Kopee.Migrations
{
    [DbContext(typeof(NopObjectContext))]
    [Migration("20211122145358_InitProductDb")]
    partial class InitProductDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Myrmica.Entity.BRANCH", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CLIENTID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CLIENT_ID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IMAGE")
                        .HasColumnType("longtext");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MAP")
                        .HasColumnType("longtext");

                    b.Property<string>("NAME")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CLIENTID");

                    b.ToTable("BRANCH");
                });

            modelBuilder.Entity("Myrmica.Entity.CATEGORY", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BANNER_ID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CATEGORY_PARENT_ID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CLIENTID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CLIENT_ID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NAME")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PARENT_CATEGORYID")
                        .HasColumnType("char(36)");

                    b.Property<string>("ROUTE")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SERVICE_TYPEID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SERVICE_TYPE_ID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CLIENTID");

                    b.HasIndex("PARENT_CATEGORYID");

                    b.HasIndex("SERVICE_TYPEID");

                    b.ToTable("CATEGORY");
                });

            modelBuilder.Entity("Myrmica.Entity.CLIENT", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NAME")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("CLIENT");
                });

            modelBuilder.Entity("Myrmica.Entity.CLIENT_SETTINGS", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CLIENTID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CLIENT_ID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KEY")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SETTING_TYPEID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SETTING_TYPE_ID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VALUE")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("CLIENTID");

                    b.HasIndex("SETTING_TYPEID");

                    b.ToTable("CLIENT_SETTINGS");
                });

            modelBuilder.Entity("Myrmica.Entity.CONTACT", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CLIENTID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CLIENT_ID")
                        .HasColumnType("char(36)");

                    b.Property<string>("CONTENT")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("longtext");

                    b.Property<string>("FULLNAME")
                        .HasColumnType("longtext");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LOCATION")
                        .HasColumnType("longtext");

                    b.Property<string>("PHONENUMBER")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CLIENTID");

                    b.ToTable("CONTACT");
                });

            modelBuilder.Entity("Myrmica.Entity.Demo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Demo");
                });

            modelBuilder.Entity("Myrmica.Entity.MENU", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CLIENTID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CLIENT_ID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MENU_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<int>("ORDER")
                        .HasColumnType("int");

                    b.Property<Guid?>("PARENT_ID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PARENT_MENUID")
                        .HasColumnType("char(36)");

                    b.Property<string>("ROUTE")
                        .HasColumnType("longtext");

                    b.Property<string>("TITLE")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CLIENTID");

                    b.HasIndex("PARENT_MENUID");

                    b.ToTable("MENU");
                });

            modelBuilder.Entity("Myrmica.Entity.NEWS", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BANNER_ID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BANNER_SPECIAL_ID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CATEGORYID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CATEGORY_ID")
                        .HasColumnType("char(36)");

                    b.Property<string>("CONTENT")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FULL_DESCRIPTION")
                        .HasColumnType("longtext");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_SPECIAL")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ROUTE")
                        .HasColumnType("longtext");

                    b.Property<string>("SHORT_DESCRIPTION")
                        .HasColumnType("longtext");

                    b.Property<string>("TITLE")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORYID");

                    b.ToTable("NEWS");
                });

            modelBuilder.Entity("Myrmica.Entity.PRODUCT", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BANNER_ID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CATEGORYID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CATEGORY_ID")
                        .HasColumnType("char(36)");

                    b.Property<string>("CONTENT")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FULL_DESCRIPTION")
                        .HasColumnType("longtext");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DISCOUNT")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_HOT")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_NEW")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_SPECIAL")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NAME")
                        .HasColumnType("longtext");

                    b.Property<double>("PRICE")
                        .HasColumnType("double");

                    b.Property<string>("ROUTE")
                        .HasColumnType("longtext");

                    b.Property<string>("SHORT_DESCRIPTION")
                        .HasColumnType("longtext");

                    b.Property<string>("SLIDE_IMAGE_IDS")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("THUMBNAIL_ID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORYID");

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("Myrmica.Entity.SERVICE_TYPE", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TITLE")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("SERVICE_TYPE");
                });

            modelBuilder.Entity("Myrmica.Entity.SETTING_TYPE", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DELETED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TITLE")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("SETTING_TYPE");
                });

            modelBuilder.Entity("Myrmica.Entity.BRANCH", b =>
                {
                    b.HasOne("Myrmica.Entity.CLIENT", "CLIENT")
                        .WithMany("BRANCHES")
                        .HasForeignKey("CLIENTID");

                    b.Navigation("CLIENT");
                });

            modelBuilder.Entity("Myrmica.Entity.CATEGORY", b =>
                {
                    b.HasOne("Myrmica.Entity.CLIENT", "CLIENT")
                        .WithMany("CATEGORIES")
                        .HasForeignKey("CLIENTID");

                    b.HasOne("Myrmica.Entity.CATEGORY", "PARENT_CATEGORY")
                        .WithMany("CHILD_CATEGORY")
                        .HasForeignKey("PARENT_CATEGORYID");

                    b.HasOne("Myrmica.Entity.SERVICE_TYPE", "SERVICE_TYPE")
                        .WithMany("CATEGORIES")
                        .HasForeignKey("SERVICE_TYPEID");

                    b.Navigation("CLIENT");

                    b.Navigation("PARENT_CATEGORY");

                    b.Navigation("SERVICE_TYPE");
                });

            modelBuilder.Entity("Myrmica.Entity.CLIENT_SETTINGS", b =>
                {
                    b.HasOne("Myrmica.Entity.CLIENT", "CLIENT")
                        .WithMany("CLIENT_SETTINGS")
                        .HasForeignKey("CLIENTID");

                    b.HasOne("Myrmica.Entity.SETTING_TYPE", "SETTING_TYPE")
                        .WithMany("CLIENT_SETTINGS")
                        .HasForeignKey("SETTING_TYPEID");

                    b.Navigation("CLIENT");

                    b.Navigation("SETTING_TYPE");
                });

            modelBuilder.Entity("Myrmica.Entity.CONTACT", b =>
                {
                    b.HasOne("Myrmica.Entity.CLIENT", "CLIENT")
                        .WithMany("CONTACTS")
                        .HasForeignKey("CLIENTID");

                    b.Navigation("CLIENT");
                });

            modelBuilder.Entity("Myrmica.Entity.MENU", b =>
                {
                    b.HasOne("Myrmica.Entity.CLIENT", "CLIENT")
                        .WithMany("MENUS")
                        .HasForeignKey("CLIENTID");

                    b.HasOne("Myrmica.Entity.MENU", "PARENT_MENU")
                        .WithMany("CHILD_MENU")
                        .HasForeignKey("PARENT_MENUID");

                    b.Navigation("CLIENT");

                    b.Navigation("PARENT_MENU");
                });

            modelBuilder.Entity("Myrmica.Entity.NEWS", b =>
                {
                    b.HasOne("Myrmica.Entity.CATEGORY", "CATEGORY")
                        .WithMany("NEWS")
                        .HasForeignKey("CATEGORYID");

                    b.Navigation("CATEGORY");
                });

            modelBuilder.Entity("Myrmica.Entity.PRODUCT", b =>
                {
                    b.HasOne("Myrmica.Entity.CATEGORY", "CATEGORY")
                        .WithMany("PRODUCTS")
                        .HasForeignKey("CATEGORYID");

                    b.Navigation("CATEGORY");
                });

            modelBuilder.Entity("Myrmica.Entity.CATEGORY", b =>
                {
                    b.Navigation("CHILD_CATEGORY");

                    b.Navigation("NEWS");

                    b.Navigation("PRODUCTS");
                });

            modelBuilder.Entity("Myrmica.Entity.CLIENT", b =>
                {
                    b.Navigation("BRANCHES");

                    b.Navigation("CATEGORIES");

                    b.Navigation("CLIENT_SETTINGS");

                    b.Navigation("CONTACTS");

                    b.Navigation("MENUS");
                });

            modelBuilder.Entity("Myrmica.Entity.MENU", b =>
                {
                    b.Navigation("CHILD_MENU");
                });

            modelBuilder.Entity("Myrmica.Entity.SERVICE_TYPE", b =>
                {
                    b.Navigation("CATEGORIES");
                });

            modelBuilder.Entity("Myrmica.Entity.SETTING_TYPE", b =>
                {
                    b.Navigation("CLIENT_SETTINGS");
                });
#pragma warning restore 612, 618
        }
    }
}
